apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-1112
spec:
  selector:
    matchLabels:
      app: mysql-1112
  serviceName: "mysql-1112"
  template:
    metadata:
      labels:
        app: mysql-1112
    spec:
      initContainers:
        - name: init-mysql
          image: mysql:latest
          command:
            - /bin/sh
            - "-c"
            - |
              until mysqladmin ping -h 127.0.0.1 --silent; do
                echo "Waiting for MySQL to be ready..."
                sleep 2
              done
              echo "MySQL is ready. Initializing database..."
              mysql -h 127.0.0.1 -u root -p"$MYSQL_ROOT_PASSWORD" < /docker-entrypoint-initdb.d/mysql_dump.sql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1112"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: init-sql      
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-sql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1112"
      volumes:
        - name: init-sql
          configMap:
            name: mysql-init-sql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---  
apiVersion: v1
kind: Service
metadata:
  name: mysql-1112
spec:
  selector:
    app: mysql-1112
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP