apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
  namespace: k8s-study-group
  labels:
    app: todo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      name: todo-server
      labels:
        app: todo-server
    spec:
      containers:
        - name: todo-server
          image: vul358/to-do-list:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: MYSQL_HOST_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: MYSQL_ROOT_PASSWORD
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-server
  namespace: k8s-study-group
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-server
                port:
                  number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-server-svc
  namespace: k8s-study-group
spec:
  selector:
    app: todo-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000